version: 2
config_android:
  docker:
    - image: circleci/android:api-29
  working_directory: ~/project
  environment:
    JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb
    FASTLANE_LANE_LINT: linting
    FASTLANE_LANE_TEST: unit_tests
jobs:
  build_and_setup:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/project
    environment:
      - JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
      - GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
      - TERM: dumb
      - FASTLANE_LANE_LINT: linting
      - FASTLANE_LANE_TEST: unit_tests
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Download Dependencies
          command: |
            echo "GOOGLE_MAPS_API_KEY_DEBUG=$GOOGLE_MAPS_API_KEY_DEBUG" > app/secure.properties
            echo "GOOGLE_MAPS_API_KEY_RELEASE=$GOOGLE_MAPS_API_KEY_RELEASE" >> app/secure.properties
            echo "KARHOO_SEGMENT_API_KEY_SANDBOX=\"$KARHOO_SEGMENT_API_KEY_SANDBOX\"" >> app/secure.properties
            echo "KARHOO_SEGMENT_API_KEY_PROD=\"$KARHOO_SEGMENT_API_KEY_PROD\"" >> app/secure.properties
            echo "ADYEN_GUEST_CHECKOUT_IDENTIFIER=\"ADYEN_GUEST_CHECKOUT_IDENTIFIER\"" >> app/secure.properties
            echo "ADYEN_GUEST_CHECKOUT_ORGANISATION_ID=\"$ADYEN_GUEST_CHECKOUT_ORGANISATION_ID\"" >> app/secure.properties
            echo "BRAINTREE_GUEST_CHECKOUT_IDENTIFIER=\"$BRAINTREE_GUEST_CHECKOUT_IDENTIFIER\"" >> app/secure.properties
            echo "BRAINTREE_GUEST_CHECKOUT_ORGANISATION_ID=\"$BRAINTREE_GUEST_CHECKOUT_ORGANISATION_ID\"" >> app/secure.properties
            echo "GUEST_CHECKOUT_REFERER=\"$GUEST_CHECKOUT_REFERER\"" >> app/secure.properties
            echo "ADYEN_CLIENT_ID=\"ADYEN_CLIENT_ID\"" >> app/secure.properties
            echo "ADYEN_CLIENT_SCOPE=\"ADYEN_CLIENT_SCOPE\"" >> app/secure.properties
            echo "ADYEN_AUTH_TOKEN=\"ADYEN_AUTH_TOKEN\"" >> app/secure.properties
            echo "BRAINTREE_CLIENT_ID=\"BRAINTREE_CLIENT_ID\"" >> app/secure.properties
            echo "BRAINTREE_CLIENT_SCOPE=\"BRAINTREE_CLIENT_SCOPE\"" >> app/secure.properties
            echo "BRAINTREE_AUTH_TOKEN=\"BRAINTREE_AUTH_TOKEN\"" >> app/secure.properties
            echo "STAGING_HOST=\"$STAGING_HOST\"" >> app/secure.properties
            echo "STAGING_AUTH_HOST=\"$STAGING_AUTH_HOST\"" >> app/secure.properties
            echo "STAGING_GUEST_HOST=\"$STAGING_GUEST_HOST\"" >> app/secure.properties
            echo "ADYEN_PUBLIC_KEY=\"$ADYEN_PUBLIC_KEY\"" >> app/secure.properties
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Set properties
          command: |
                    echo "GOOGLE_MAPS_API_KEY_DEBUG=$GOOGLE_MAPS_API_KEY_DEBUG" > app/secure.properties
                    echo "GOOGLE_MAPS_API_KEY_RELEASE=$GOOGLE_MAPS_API_KEY_RELEASE" >> app/secure.properties
                    echo "KARHOO_SEGMENT_API_KEY_SANDBOX=\"$KARHOO_SEGMENT_API_KEY_SANDBOX\"" >> app/secure.properties
                    echo "KARHOO_SEGMENT_API_KEY_PROD=\"$KARHOO_SEGMENT_API_KEY_PROD\"" >> app/secure.properties
                    echo "ADYEN_GUEST_CHECKOUT_IDENTIFIER=\"ADYEN_GUEST_CHECKOUT_IDENTIFIER\"" >> app/secure.properties
                    echo "ADYEN_GUEST_CHECKOUT_ORGANISATION_ID=\"$ADYEN_GUEST_CHECKOUT_ORGANISATION_ID\"" >> app/secure.properties
                    echo "BRAINTREE_GUEST_CHECKOUT_IDENTIFIER=\"$BRAINTREE_GUEST_CHECKOUT_IDENTIFIER\"" >> app/secure.properties
                    echo "BRAINTREE_GUEST_CHECKOUT_ORGANISATION_ID=\"$BRAINTREE_GUEST_CHECKOUT_ORGANISATION_ID\"" >> app/secure.properties
                    echo "GUEST_CHECKOUT_REFERER=\"$GUEST_CHECKOUT_REFERER\"" >> app/secure.properties
                    echo "ADYEN_CLIENT_ID=\"ADYEN_CLIENT_ID\"" >> app/secure.properties
                    echo "ADYEN_CLIENT_SCOPE=\"ADYEN_CLIENT_SCOPE\"" >> app/secure.properties
                    echo "ADYEN_AUTH_TOKEN=\"ADYEN_AUTH_TOKEN\"" >> app/secure.properties
                    echo "BRAINTREE_CLIENT_ID=\"BRAINTREE_CLIENT_ID\"" >> app/secure.properties
                    echo "BRAINTREE_CLIENT_SCOPE=\"BRAINTREE_CLIENT_SCOPE\"" >> app/secure.properties
                    echo "BRAINTREE_AUTH_TOKEN=\"BRAINTREE_AUTH_TOKEN\"" >> app/secure.properties
                    echo "STAGING_HOST=\"$STAGING_HOST\"" >> app/secure.properties
                    echo "STAGING_AUTH_HOST=\"$STAGING_AUTH_HOST\"" >> app/secure.properties
                    echo "STAGING_GUEST_HOST=\"$STAGING_GUEST_HOST\"" >> app/secure.properties
                    echo "ADYEN_PUBLIC_KEY=\"$ADYEN_PUBLIC_KEY\"" >> app/secure.properties
                    sudo chmod +x ./gradlew
      
      - run:
          name: "Install Sauce Connect Client"
          command: |
            sudo apt-get update
            sudo apt-get -y install curl lsof
            ping saucelabs.com
            curl -v https://saucelabs.com/
            curl https://eu-central-1.saucelabs.com/downloads/sc-4.6.3-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
      - run:
          name: "Launch Tunnel"
          background: true
          command: |
            cd sc-*
            bin/sc --pidfile /tmp/sc.pid1 -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -i demo-js-tunnel --no-remove-colliding-tunnels --se-port 4445
      - run:
          name: "Run Espresso Tests on Virtual Devices"
          command: |
            while ! lsof -i:4445 -t; do sleep 3; done
            cd .circleci/
            sudo chmod +x ./runner.sh ./sauce-runner-virtual-0.1.2-linux/bin/sauce-runner-virtual
            ./runner.sh
      - run:
          name: "Shut Down Sauce Connect Tunnel"
          command: |
            kill -9 'cat /tmp/sc.pid1'
      - store_artifacts:
          path: ./app/build/reports
          destination: reports/
      - persist_to_workspace:
          root: .
          paths:
            - ./app/build
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
