fastlane_require 'dotenv'
ENV["FASTLANE_SKIP_UPDATE_CHECK"]="1"
ENV["FASTLANE_OPT_OUT_USAGE"]="1"
FASTLANE_HIDE_CHANGELOG = true
FASTLANE_SKIP_UPDATE_CHECK = true
fastlane_version "2.85.0"

default_platform :android

releaseNotes = sh("python GetLastChangelog.py")

default_platform :android
platform :android do

  before_all do
    ENV["SLACK_URL"] = ENV["SLACK_WEBHOOK_URL"]
    setup_circle_ci
  end

  desc "Clean"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Build Android test"
    lane :build_tests do
      gradle(task: "./gradlew assembleDebug")
      gradle(task: "./gradlew assembleAndroidTest")
      slack_result(message: "*Karhoo Android UISDK* passed unit testing")
    end

  desc "Runs all the unit tests"
  lane :unit_tests do
    gradle(task: "testDebug")
    slack_result(message: "*Karhoo Android UISDK* passed unit testing")
  end

  desc "Runs lint and detekt"
  lane :linting do
    gradle(task: "lintRelease")
    gradle(task: "detekt")
    slack_result(message: "*Karhoo Android UISDK* passed detekt and lint")
  end

# PUSH TO AppCenter
  desc "Push Sandbox to AppCenter"
    lane :pushSandbox do
      gradle(task: "assembleSandbox")
      appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_name: ENV["APPCENTER_OWNER_NAME"],
        app_name: "Karhoo-Traveller-SandBox",
        apk: "../KarhooTraveller/app/build/outputs/apk/sandbox/app-sandbox.apk",
        notify_testers: true,
        release_notes: releaseNotes
      )
  end

  desc "Push ProdQA to AppCenter"
  lane :pushProdQA do
    gradle(task: "assembleProdQA")
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: "Karhoo-Traveller",
      apk: "../KarhooTraveller/app/build/outputs/apk/prodQA/app-prodQA.apk",
      notify_testers: true,
      release_notes: releaseNotes
    )
  end

  desc "Push Staging to AppCenter"
  lane :pushStaging do
    gradle(task: "assembleDebug")
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: "KarhooTraveller",
      apk: "../KarhooTraveller/app/build/outputs/apk/debug/app-debug.apk",
      notify_testers: true,
      release_notes: releaseNotes
    )
  end

  desc "Push all"
  lane :pushAll do
    pushStaging
    pushProdQA
  end

  desc "Messaging"
  lane :slack_result do |values|
    message_text = values[:message]
    slack(
      channel: "#mobile_circleci_results",
      message: message_text,
      success: values[:success]
    )
  end
 end
