package com.karhoo.uisdk.util

object ViewsConstants {
        const val TRIP_ALLOCATION_ANIMATION_START_DELAY = 5000L
        const val TRIP_ALLOCATION_ANIMATION_DURATION = 600L
        const val TRIP_ALLOCATION_TEXT_ROTATION_ANIM_INITIAL_DELAY = 5400L
        const val TRIP_ALLOCATION_TEXT_ROTATION_ANIM_DURATION = 100L
        const val TRIP_ALLOCATION_TEXT_ROTATION_ANIM_START_OFFSET_SHORT = 200L
        const val TRIP_ALLOCATION_TEXT_ROTATION_ANIM_START_OFFSET_LONG = 4000L

        const val ETA_ELEVATION = 10F

        const val TRIP_MAP_DRIVER_ZINDEX = 1.5f
        const val TRIP_MAP_CAMERA_ZOOM_WIDTH_PADDING = 0.20

        const val DRIVER_PHOTO_ACTIVITY_NAME_ANIM_START_OFFSET = 50L

        const val BOOKING_MAP_PICKUP_GEOCODE_DELAY = 1000L
        const val BOOKING_MAP_DESTINATION_MARKER_MAX_ZOOM_PREFERENCE = 20f
        const val BOOKING_MAP_PICKUP_MARKER_MAX_ZOOM_PREFERENCE_DEFAULT = 18f
        const val BOOKING_MAP_CAMERA_ZOOM_WIDTH_PADDING = 0.20
        const val BOOKING_MAP_PREBOOK_CONF_DIALOG_WIDTH_HEIGHT_FACTOR = 0.6

}
